### ISSUE TITLE
Enforce BMP validation

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/tr-55#34]
Some land use areas are not suitable for certain BMP placements.  We need to determine the proper combinations and thresholds of land use values that will accept a given bmp.

**Comment by jamesmcclain** [comment]
No all BMPs work on all soil types.  According to [the table](https://github.com/WikiWatershed/tr-55/blob/1818c56e293b0ed09d373aff351be2c6f32d9e68/tr55/tables.py#L412-L417) *Green Roof* works on all four soil types, but *Porous Paving*, *Infiltration Trench*, and *Rain Garden* do not work on soil type D.

**Comment by mmcfarland** [comment]
Stroud is investigating and will provide table values for conservation practices on soil type D

**Comment by SRGDamia1** [comment]
I'm sorry, I totally missed this being in our court.  I'll talk to @aufdenkampe and Melinda about this.

**Comment by SRGDamia1** [comment]
Per Melinda:  No luck at all [in finding numbers for soil type D].  However, since the infiltration rate for type D seems to fairly consistently be reported as 1/3 that of type C, lets take the rates for BMPs reported for type C, derive a third of that and use that for type D.  So type D rate = 1/3(type C rate).
